---

- name: Quick test
  hosts: htpc
  tasks:
    - name: Testing Authentication
      debug:
        msg: " This is a test. PASSED!!!! "
     
    - name: Patch htpc
      become: True
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid: yes
