---

- name: Quick test
  hosts: htpc
  tasks:
    - name: Testing Authentication
      debug:
        msg: " *** Patch Begins *** "
        
    - name: removing unused deps
      become: True
      apt:
        autoremove: yes
     
    - name: Updating main server
      become: True
      apt: name="*" state=latest
      ignore_errors: True
      
    - name: Additional Steps
      shell: apt-get update
      become: True
      become_user: root
