---

- name: Quick test
  hosts: htpc
  tasks:
    - name: Testing Authentication
      debug:
        msg: " *** Patch Begins *** "
     
    - name: Updating main server
      become: True
      apt: name="*" state=latest
      
    - name: Additional Steps
      shell: apt-get update
      become: True
      become_user: root
