---

- name: Quick test
  hosts: htpc
  tasks:
    - name: Testing Authentication
      debug:
        msg: " Hello, Authentication worked fine "
     
    - name: Touching file
      file: path=/tmp/oz.conf state=touch
