version: 2.1


commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  a_job:
    docker:
      - image: circleci/node
    steps:
      - print_pipeline_id

workflows:
  my_workflow:
    jobs:
      - a_job