version: 2.1

jobs:
  save-file:
    docker:
      - image: python:3.7-alpine3.11
    parallelism: 2
    steps:
      - run:
          name: This is one JOB.
          command: | 
            echo " ++++ I like Gitlab Better ++++++"
      - checkout
      - run: 
          name: save a file with vars
          command: | 
            cat \<< EOF >> ~/env
            ENVIRONMENT=production
            VERSION=1
            TYPEORM_CONNECTION=postgres
            TYPEORM_MIGRATIONS_DIR=./src/migrations
            TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
            TYPEORM_MIGRATIONS=./src/migrations/*.ts
            EOF
    
  eat-popcorn:
    docker: 
      - image: cimg/base:2021.04
    steps:
      - checkout
      - save_cache:
          key: MyKey
          paths:
            - ~/my-cache
      - run:
          name: Getting some packages installed
          command: |
            sudo apt install unzip tar -y
            echo "Who let the dogs out"
  
  hit-target:
    docker: 
      - image: python:3.7-alpine3.11
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys: 
            - MyKey
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/
      - add_ssh_keys:
          fingerprints: 
            - 'ae:9a:e0:ba:57:25:4e:55:2e:7f:61:38:b3:5a:6f:e8'
      - run:
          name: "Aquiring Target"
          command: |
            apk add --update ansible openssh-client tar gzip curl nodejs npm
      - run:
          name: "Missile Launch ... Destroy Destroy"
          no_output_timeout: 20m
          command: |
            cd .circleci/ansible
            ansible-playbook -i ./circleci/ansible/inventory.txt ./circleci/ansible/fleetcmdr.yml
            


workflows:
  test-workflow:
    jobs:
      - save-file
      - eat-popcorn
      - hit-target
# version: 2.1


# commands:
#   print_pipeline_id:
#     steps:
#       - run: echo $CIRCLE_WORKFLOW_ID

# jobs:
#   a_job:
#     docker:
#       - image: circleci/node
#     steps:
#       - print_pipeline_id

#   a_job_that_fails:
#     docker:
#       - circleci/node:13.8.0
#     steps: 
#       - run: exit 1 

#   run:
#     name: running when it fails and it hurts
#     command: |
#       echo " I ran because your other job failed "
#     when: on_fail

# workflows:
#   my_workflow:
#     jobs:
#       - a_job