version: 2.1



jobs:
  save-file:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - command: | 
          cat \<< EOF >> env
            ENVIRONMENT=production
            VERSION=1
            TYPEORM_CONNECTION=postgres
            TYPEORM_MIGRATIONS_DIR=./src/migrations
            TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
            TYPEORM_MIGRATIONS=./src/migrations/*.ts
            EOF
      - persist_to_workspace:
          root: ~/
          paths:
            - env

      - run:
          name: Get me the content of env
          command: |
            cat ~/env

workflows:
  build:
    jobs:
      - save-file


# version: 2.1


# commands:
#   print_pipeline_id:
#     steps:
#       - run: echo $CIRCLE_WORKFLOW_ID

# jobs:
#   a_job:
#     docker:
#       - image: circleci/node
#     steps:
#       - print_pipeline_id

#   a_job_that_fails:
#     docker:
#       - circleci/node:13.8.0
#     steps: 
#       - run: exit 1 

#   run:
#     name: running when it fails and it hurts
#     command: |
#       echo " I ran because your other job failed "
#     when: on_fail

# workflows:
#   my_workflow:
#     jobs:
#       - a_job