version: 2.1

jobs:
  save-file:
    docker:
      - image: python:3.7-alpine3.11
    parallelism: 2
    steps:
      - run:
          name: This is one JOB.
          command: | 
            echo " ++++ I like Gitlab Better ++++++"
      - checkout
      - run: 
          name: save a file with vars
          command: | 
            cat \<< EOF >> ~/env
            ENVIRONMENT=production
            VERSION=1
            TYPEORM_CONNECTION=postgres
            TYPEORM_MIGRATIONS_DIR=./src/migrations
            TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
            TYPEORM_MIGRATIONS=./src/migrations/*.ts
            EOF
      - persist_to_workspace:
          root: ~/
          paths:
            - env
      - run:
          name: Get me the content of env
          command: |
            cat ~/env
            pwd 
            ls -l 
            stat ~/env 
            touch iphone.log
      - persist_to_workspace:
          root: .
          paths:
            - "*"
    
  eat-popcorn:
    docker: 
      - image: cimg/base:2021.04
    steps:
      - checkout
      - save_cache:
          key: MyKey
          paths:
            - ~/my-cache
      - run:
          name: Getting some packages installed
          command: |
            sudo apt install unzip tar -y
            echo "Who let the dogs out"
  
  cleaner:
    docker: 
      - image: python:3.7-alpine3.11
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys: 
            - MyKey
      - run: 
          name: installing a few deps
          command: |
            pwd
            apk add --update ansible curl tar
            ls     
            ansible-playbook helloworld.yml 
      - attach_workspace:
          at: .

      - run:
          name: Checking the log
          command: |
            ls /
            sudo find / -name iphone.log

workflows:
  test-workflow:
    jobs:
      - save-file
      - eat-popcorn
      - cleaner
# version: 2.1


# commands:
#   print_pipeline_id:
#     steps:
#       - run: echo $CIRCLE_WORKFLOW_ID

# jobs:
#   a_job:
#     docker:
#       - image: circleci/node
#     steps:
#       - print_pipeline_id

#   a_job_that_fails:
#     docker:
#       - circleci/node:13.8.0
#     steps: 
#       - run: exit 1 

#   run:
#     name: running when it fails and it hurts
#     command: |
#       echo " I ran because your other job failed "
#     when: on_fail

# workflows:
#   my_workflow:
#     jobs:
#       - a_job