version: 2.1
jobs:
  commands:
    print_pipeline_id:
      description: "This will print out the pipeline ID"
      parameters:
        to:
          type: string
          default: "Hi you!"
      steps:
        - run: echo $CIRCLE_WORKFLOW_ID


workflows:
  my_workflow:
    jobs:
      - print_pipeline_id:
      