
version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello Bori"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "cua"
  print_myVar:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo $CIRCLE_USERNAME


workflows:
  welcome:
    jobs:
      
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_myVar
          
